"""empty message

Revision ID: 38907a7a80c7
Revises: d371c5c61523
Create Date: 2024-02-15 13:39:59.306698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38907a7a80c7'
down_revision = 'd371c5c61523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
