"""empty message

Revision ID: 70188b44db05
Revises: 7a06fada0af7
Create Date: 2024-02-19 16:54:40.259022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70188b44db05'
down_revision = '7a06fada0af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
